ARB_PRECOMPILES = {
    "0x0000000000000000000000000000000000000064": [
        {
            "inputs": [
                {"internalType": "uint256", "name": "requested", "type": "uint256"},
                {"internalType": "uint256", "name": "current", "type": "uint256"},
            ],
            "name": "InvalidBlockNumber",
            "selector": "0xd5dc642d",
            "signature": "InvalidBlockNumber(uint256,uint256)",
            "type": "error",
        },
        {
            "anonymous": False,
            "inputs": [
                {
                    "indexed": False,
                    "internalType": "address",
                    "name": "caller",
                    "type": "address",
                },
                {
                    "indexed": True,
                    "internalType": "address",
                    "name": "destination",
                    "type": "address",
                },
                {
                    "indexed": True,
                    "internalType": "uint256",
                    "name": "uniqueId",
                    "type": "uint256",
                },
                {
                    "indexed": True,
                    "internalType": "uint256",
                    "name": "batchNumber",
                    "type": "uint256",
                },
                {
                    "indexed": False,
                    "internalType": "uint256",
                    "name": "indexInBatch",
                    "type": "uint256",
                },
                {
                    "indexed": False,
                    "internalType": "uint256",
                    "name": "arbBlockNum",
                    "type": "uint256",
                },
                {
                    "indexed": False,
                    "internalType": "uint256",
                    "name": "ethBlockNum",
                    "type": "uint256",
                },
                {
                    "indexed": False,
                    "internalType": "uint256",
                    "name": "timestamp",
                    "type": "uint256",
                },
                {
                    "indexed": False,
                    "internalType": "uint256",
                    "name": "callvalue",
                    "type": "uint256",
                },
                {
                    "indexed": False,
                    "internalType": "bytes",
                    "name": "data",
                    "type": "bytes",
                },
            ],
            "name": "L2ToL1Transaction",
            "selector": "0x5baaa87db386365b5c161be377bc3d8e317e8d98d71a3ca7ed7d555340c8f767",
            "signature": "L2ToL1Transaction(address,address,uint256,uint256,uint256,uint256,uint256,uint256,uint256,bytes)",
            "type": "event",
        },
        {
            "anonymous": False,
            "inputs": [
                {
                    "indexed": False,
                    "internalType": "address",
                    "name": "caller",
                    "type": "address",
                },
                {
                    "indexed": True,
                    "internalType": "address",
                    "name": "destination",
                    "type": "address",
                },
                {
                    "indexed": True,
                    "internalType": "uint256",
                    "name": "hash",
                    "type": "uint256",
                },
                {
                    "indexed": True,
                    "internalType": "uint256",
                    "name": "position",
                    "type": "uint256",
                },
                {
                    "indexed": False,
                    "internalType": "uint256",
                    "name": "arbBlockNum",
                    "type": "uint256",
                },
                {
                    "indexed": False,
                    "internalType": "uint256",
                    "name": "ethBlockNum",
                    "type": "uint256",
                },
                {
                    "indexed": False,
                    "internalType": "uint256",
                    "name": "timestamp",
                    "type": "uint256",
                },
                {
                    "indexed": False,
                    "internalType": "uint256",
                    "name": "callvalue",
                    "type": "uint256",
                },
                {
                    "indexed": False,
                    "internalType": "bytes",
                    "name": "data",
                    "type": "bytes",
                },
            ],
            "name": "L2ToL1Tx",
            "selector": "0x3e7aafa77dbf186b7fd488006beff893744caa3c4f6f299e8a709fa2087374fc",
            "signature": "L2ToL1Tx(address,address,uint256,uint256,uint256,uint256,uint256,uint256,bytes)",
            "type": "event",
        },
        {
            "anonymous": False,
            "inputs": [
                {
                    "indexed": True,
                    "internalType": "uint256",
                    "name": "reserved",
                    "type": "uint256",
                },
                {
                    "indexed": True,
                    "internalType": "bytes32",
                    "name": "hash",
                    "type": "bytes32",
                },
                {
                    "indexed": True,
                    "internalType": "uint256",
                    "name": "position",
                    "type": "uint256",
                },
            ],
            "name": "SendMerkleUpdate",
            "selector": "0xe9e13da364699fb5b0496ff5a0fc70760ad5836e93ba96568a4e42b9914a8b95",
            "signature": "SendMerkleUpdate(uint256,bytes32,uint256)",
            "type": "event",
        },
        {
            "inputs": [
                {"internalType": "uint256", "name": "arbBlockNum", "type": "uint256"}
            ],
            "name": "arbBlockHash",
            "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}],
            "selector": "0x2b407a82",
            "signature": "arbBlockHash(uint256)",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "arbBlockNumber",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0xa3b1b31d",
            "signature": "arbBlockNumber()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "arbChainID",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0xd127f54a",
            "signature": "arbChainID()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "arbOSVersion",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0x051038f2",
            "signature": "arbOSVersion()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getStorageGasAvailable",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0xa94597ff",
            "signature": "getStorageGasAvailable()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "isTopLevelCall",
            "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
            "selector": "0x08bd624c",
            "signature": "isTopLevelCall()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "address", "name": "sender", "type": "address"},
                {"internalType": "address", "name": "unused", "type": "address"},
            ],
            "name": "mapL1SenderContractAddressToL2Alias",
            "outputs": [{"internalType": "address", "name": "", "type": "address"}],
            "selector": "0x4dbbd506",
            "signature": "mapL1SenderContractAddressToL2Alias(address,address)",
            "stateMutability": "pure",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "myCallersAddressWithoutAliasing",
            "outputs": [{"internalType": "address", "name": "", "type": "address"}],
            "selector": "0xd74523b3",
            "signature": "myCallersAddressWithoutAliasing()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "sendMerkleTreeState",
            "outputs": [
                {"internalType": "uint256", "name": "size", "type": "uint256"},
                {"internalType": "bytes32", "name": "root", "type": "bytes32"},
                {"internalType": "bytes32[]", "name": "partials", "type": "bytes32[]"},
            ],
            "selector": "0x7aeecd2a",
            "signature": "sendMerkleTreeState()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "address", "name": "destination", "type": "address"},
                {"internalType": "bytes", "name": "data", "type": "bytes"},
            ],
            "name": "sendTxToL1",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0x928c169a",
            "signature": "sendTxToL1(address,bytes)",
            "stateMutability": "payable",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "wasMyCallersAddressAliased",
            "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
            "selector": "0x175a260b",
            "signature": "wasMyCallersAddressAliased()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "address", "name": "destination", "type": "address"}
            ],
            "name": "withdrawEth",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0x25e16063",
            "signature": "withdrawEth(address)",
            "stateMutability": "payable",
            "type": "function",
        },
    ],
    "0x0000000000000000000000000000000000000065": [
        {
            "inputs": [
                {"internalType": "address", "name": "account", "type": "address"}
            ],
            "name": "getBalance",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0xf8b2cb4f",
            "signature": "getBalance(address)",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "address", "name": "account", "type": "address"}
            ],
            "name": "getCode",
            "outputs": [{"internalType": "bytes", "name": "", "type": "bytes"}],
            "selector": "0x7e105ce2",
            "signature": "getCode(address)",
            "stateMutability": "view",
            "type": "function",
        },
    ],
    "0x0000000000000000000000000000000000000066": [
        {
            "inputs": [{"internalType": "address", "name": "addr", "type": "address"}],
            "name": "addressExists",
            "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
            "selector": "0xa5025222",
            "signature": "addressExists(address)",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [{"internalType": "address", "name": "addr", "type": "address"}],
            "name": "compress",
            "outputs": [{"internalType": "bytes", "name": "", "type": "bytes"}],
            "selector": "0xf6a455a2",
            "signature": "compress(address)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "bytes", "name": "buf", "type": "bytes"},
                {"internalType": "uint256", "name": "offset", "type": "uint256"},
            ],
            "name": "decompress",
            "outputs": [
                {"internalType": "address", "name": "", "type": "address"},
                {"internalType": "uint256", "name": "", "type": "uint256"},
            ],
            "selector": "0x31862ada",
            "signature": "decompress(bytes,uint256)",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [{"internalType": "address", "name": "addr", "type": "address"}],
            "name": "lookup",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0xd4b6b5da",
            "signature": "lookup(address)",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [{"internalType": "uint256", "name": "index", "type": "uint256"}],
            "name": "lookupIndex",
            "outputs": [{"internalType": "address", "name": "", "type": "address"}],
            "selector": "0x8a186788",
            "signature": "lookupIndex(uint256)",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [{"internalType": "address", "name": "addr", "type": "address"}],
            "name": "register",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0x4420e486",
            "signature": "register(address)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "size",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0x949d225d",
            "signature": "size()",
            "stateMutability": "view",
            "type": "function",
        },
    ],
    "0x0000000000000000000000000000000000000068": [
        {
            "inputs": [
                {"internalType": "address", "name": "addr", "type": "address"},
                {"internalType": "uint256", "name": "index", "type": "uint256"},
            ],
            "name": "get",
            "outputs": [
                {"internalType": "uint256", "name": "", "type": "uint256"},
                {"internalType": "bool", "name": "", "type": "bool"},
                {"internalType": "uint256", "name": "", "type": "uint256"},
            ],
            "selector": "0xb464631b",
            "signature": "get(address,uint256)",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [{"internalType": "address", "name": "addr", "type": "address"}],
            "name": "size",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0x88987068",
            "signature": "size(address)",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [{"internalType": "bytes", "name": "buf", "type": "bytes"}],
            "name": "upload",
            "outputs": [],
            "selector": "0xce2ae159",
            "signature": "upload(bytes)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
    ],
    "0x0000000000000000000000000000000000000069": {
        "inputs": [{"internalType": "uint256", "name": "gasAmount", "type": "uint256"}],
        "name": "burnArbGas",
        "outputs": [],
        "selector": "0xbb3480f9",
        "signature": "burnArbGas(uint256)",
        "stateMutability": "pure",
        "type": "function",
    },
    "0x000000000000000000000000000000000000006b": [
        {
            "inputs": [],
            "name": "getAllChainOwners",
            "outputs": [{"internalType": "address[]", "name": "", "type": "address[]"}],
            "selector": "0x516b4e0f",
            "signature": "getAllChainOwners()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getInfraFeeAccount",
            "outputs": [{"internalType": "address", "name": "", "type": "address"}],
            "selector": "0xee95a824",
            "signature": "getInfraFeeAccount()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getNetworkFeeAccount",
            "outputs": [{"internalType": "address", "name": "", "type": "address"}],
            "selector": "0x2d9125e9",
            "signature": "getNetworkFeeAccount()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [{"internalType": "address", "name": "addr", "type": "address"}],
            "name": "isChainOwner",
            "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
            "selector": "0x26ef7f68",
            "signature": "isChainOwner(address)",
            "stateMutability": "view",
            "type": "function",
        },
    ],
    "0x000000000000000000000000000000000000006c": [
        {
            "inputs": [],
            "name": "getAmortizedCostCapBips",
            "outputs": [{"internalType": "uint64", "name": "", "type": "uint64"}],
            "selector": "0x7a7d6beb",
            "signature": "getAmortizedCostCapBips()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getCurrentTxL1GasFees",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0xc6f7de0e",
            "signature": "getCurrentTxL1GasFees()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getGasAccountingParams",
            "outputs": [
                {"internalType": "uint256", "name": "", "type": "uint256"},
                {"internalType": "uint256", "name": "", "type": "uint256"},
                {"internalType": "uint256", "name": "", "type": "uint256"},
            ],
            "selector": "0x612af178",
            "signature": "getGasAccountingParams()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getGasBacklog",
            "outputs": [{"internalType": "uint64", "name": "", "type": "uint64"}],
            "selector": "0x1d5b5c20",
            "signature": "getGasBacklog()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getGasBacklogTolerance",
            "outputs": [{"internalType": "uint64", "name": "", "type": "uint64"}],
            "selector": "0x25754f91",
            "signature": "getGasBacklogTolerance()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getL1BaseFeeEstimate",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0xf5d6ded7",
            "signature": "getL1BaseFeeEstimate()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getL1BaseFeeEstimateInertia",
            "outputs": [{"internalType": "uint64", "name": "", "type": "uint64"}],
            "selector": "0x29eb31ee",
            "signature": "getL1BaseFeeEstimateInertia()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getL1FeesAvailable",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0x5b39d23c",
            "signature": "getL1FeesAvailable()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getL1GasPriceEstimate",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0x055f362f",
            "signature": "getL1GasPriceEstimate()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getL1PricingSurplus",
            "outputs": [{"internalType": "int256", "name": "", "type": "int256"}],
            "selector": "0x520acdd7",
            "signature": "getL1PricingSurplus()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getMinimumGasPrice",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0xf918379a",
            "signature": "getMinimumGasPrice()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getPerBatchGasCharge",
            "outputs": [{"internalType": "int64", "name": "", "type": "int64"}],
            "selector": "0x6ecca45a",
            "signature": "getPerBatchGasCharge()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getPricesInArbGas",
            "outputs": [
                {"internalType": "uint256", "name": "", "type": "uint256"},
                {"internalType": "uint256", "name": "", "type": "uint256"},
                {"internalType": "uint256", "name": "", "type": "uint256"},
            ],
            "selector": "0x02199f34",
            "signature": "getPricesInArbGas()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "address", "name": "aggregator", "type": "address"}
            ],
            "name": "getPricesInArbGasWithAggregator",
            "outputs": [
                {"internalType": "uint256", "name": "", "type": "uint256"},
                {"internalType": "uint256", "name": "", "type": "uint256"},
                {"internalType": "uint256", "name": "", "type": "uint256"},
            ],
            "selector": "0x7a1ea732",
            "signature": "getPricesInArbGasWithAggregator(address)",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getPricesInWei",
            "outputs": [
                {"internalType": "uint256", "name": "", "type": "uint256"},
                {"internalType": "uint256", "name": "", "type": "uint256"},
                {"internalType": "uint256", "name": "", "type": "uint256"},
                {"internalType": "uint256", "name": "", "type": "uint256"},
                {"internalType": "uint256", "name": "", "type": "uint256"},
                {"internalType": "uint256", "name": "", "type": "uint256"},
            ],
            "selector": "0x41b247a8",
            "signature": "getPricesInWei()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "address", "name": "aggregator", "type": "address"}
            ],
            "name": "getPricesInWeiWithAggregator",
            "outputs": [
                {"internalType": "uint256", "name": "", "type": "uint256"},
                {"internalType": "uint256", "name": "", "type": "uint256"},
                {"internalType": "uint256", "name": "", "type": "uint256"},
                {"internalType": "uint256", "name": "", "type": "uint256"},
                {"internalType": "uint256", "name": "", "type": "uint256"},
                {"internalType": "uint256", "name": "", "type": "uint256"},
            ],
            "selector": "0xba9c916e",
            "signature": "getPricesInWeiWithAggregator(address)",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getPricingInertia",
            "outputs": [{"internalType": "uint64", "name": "", "type": "uint64"}],
            "selector": "0x3dfb45b9",
            "signature": "getPricingInertia()",
            "stateMutability": "view",
            "type": "function",
        },
    ],
    "0x000000000000000000000000000000000000006d": [
        {
            "inputs": [
                {"internalType": "address", "name": "newBatchPoster", "type": "address"}
            ],
            "name": "addBatchPoster",
            "outputs": [],
            "selector": "0xdf41e1e2",
            "signature": "addBatchPoster(address)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getBatchPosters",
            "outputs": [{"internalType": "address[]", "name": "", "type": "address[]"}],
            "selector": "0xe10573a3",
            "signature": "getBatchPosters()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getDefaultAggregator",
            "outputs": [{"internalType": "address", "name": "", "type": "address"}],
            "selector": "0x875883f2",
            "signature": "getDefaultAggregator()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "address", "name": "batchPoster", "type": "address"}
            ],
            "name": "getFeeCollector",
            "outputs": [{"internalType": "address", "name": "", "type": "address"}],
            "selector": "0x9c2c5bb5",
            "signature": "getFeeCollector(address)",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [{"internalType": "address", "name": "addr", "type": "address"}],
            "name": "getPreferredAggregator",
            "outputs": [
                {"internalType": "address", "name": "", "type": "address"},
                {"internalType": "bool", "name": "", "type": "bool"},
            ],
            "selector": "0x52f10740",
            "signature": "getPreferredAggregator(address)",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "address", "name": "aggregator", "type": "address"}
            ],
            "name": "getTxBaseFee",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0x049764af",
            "signature": "getTxBaseFee(address)",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "address", "name": "batchPoster", "type": "address"},
                {
                    "internalType": "address",
                    "name": "newFeeCollector",
                    "type": "address",
                },
            ],
            "name": "setFeeCollector",
            "outputs": [],
            "selector": "0x29149799",
            "signature": "setFeeCollector(address,address)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "address", "name": "aggregator", "type": "address"},
                {"internalType": "uint256", "name": "feeInL1Gas", "type": "uint256"},
            ],
            "name": "setTxBaseFee",
            "outputs": [],
            "selector": "0x5be6888b",
            "signature": "setTxBaseFee(address,uint256)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
    ],
    "0x000000000000000000000000000000000000006e": [
        {
            "inputs": [],
            "name": "NoTicketWithID",
            "selector": "0x80698456",
            "signature": "NoTicketWithID()",
            "type": "error",
        },
        {
            "inputs": [],
            "name": "NotCallable",
            "selector": "0x902824c1",
            "signature": "NotCallable()",
            "type": "error",
        },
        {
            "anonymous": False,
            "inputs": [
                {
                    "indexed": True,
                    "internalType": "bytes32",
                    "name": "ticketId",
                    "type": "bytes32",
                }
            ],
            "name": "Canceled",
            "selector": "0x134fdd648feeaf30251f0157f9624ef8608ff9a042aad6d13e73f35d21d3f88d",
            "signature": "Canceled(bytes32)",
            "type": "event",
        },
        {
            "anonymous": False,
            "inputs": [
                {
                    "indexed": True,
                    "internalType": "bytes32",
                    "name": "ticketId",
                    "type": "bytes32",
                },
                {
                    "indexed": False,
                    "internalType": "uint256",
                    "name": "newTimeout",
                    "type": "uint256",
                },
            ],
            "name": "LifetimeExtended",
            "selector": "0xf4c40a5f930e1469fcc053bf25f045253a7bad2fcc9b88c05ec1fca8e2066b83",
            "signature": "LifetimeExtended(bytes32,uint256)",
            "type": "event",
        },
        {
            "anonymous": False,
            "inputs": [
                {
                    "indexed": True,
                    "internalType": "bytes32",
                    "name": "ticketId",
                    "type": "bytes32",
                },
                {
                    "indexed": True,
                    "internalType": "bytes32",
                    "name": "retryTxHash",
                    "type": "bytes32",
                },
                {
                    "indexed": True,
                    "internalType": "uint64",
                    "name": "sequenceNum",
                    "type": "uint64",
                },
                {
                    "indexed": False,
                    "internalType": "uint64",
                    "name": "donatedGas",
                    "type": "uint64",
                },
                {
                    "indexed": False,
                    "internalType": "address",
                    "name": "gasDonor",
                    "type": "address",
                },
                {
                    "indexed": False,
                    "internalType": "uint256",
                    "name": "maxRefund",
                    "type": "uint256",
                },
                {
                    "indexed": False,
                    "internalType": "uint256",
                    "name": "submissionFeeRefund",
                    "type": "uint256",
                },
            ],
            "name": "RedeemScheduled",
            "selector": "0x5ccd009502509cf28762c67858994d85b163bb6e451f5e9df7c5e18c9c2e123e",
            "signature": "RedeemScheduled(bytes32,bytes32,uint64,uint64,address,uint256,uint256)",
            "type": "event",
        },
        {
            "anonymous": False,
            "inputs": [
                {
                    "indexed": True,
                    "internalType": "bytes32",
                    "name": "userTxHash",
                    "type": "bytes32",
                }
            ],
            "name": "Redeemed",
            "selector": "0x27fc6cca2a0e9eb6f4876c01fc7779b00cdeb7277a770ac2b844db5932449578",
            "signature": "Redeemed(bytes32)",
            "type": "event",
        },
        {
            "anonymous": False,
            "inputs": [
                {
                    "indexed": True,
                    "internalType": "bytes32",
                    "name": "ticketId",
                    "type": "bytes32",
                }
            ],
            "name": "TicketCreated",
            "selector": "0x7c793cced5743dc5f531bbe2bfb5a9fa3f40adef29231e6ab165c08a29e3dd89",
            "signature": "TicketCreated(bytes32)",
            "type": "event",
        },
        {
            "inputs": [
                {"internalType": "bytes32", "name": "ticketId", "type": "bytes32"}
            ],
            "name": "cancel",
            "outputs": [],
            "selector": "0xc4d252f5",
            "signature": "cancel(bytes32)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "bytes32", "name": "ticketId", "type": "bytes32"}
            ],
            "name": "getBeneficiary",
            "outputs": [{"internalType": "address", "name": "", "type": "address"}],
            "selector": "0xba20dda4",
            "signature": "getBeneficiary(bytes32)",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getCurrentRedeemer",
            "outputs": [{"internalType": "address", "name": "", "type": "address"}],
            "selector": "0xde4ba2b3",
            "signature": "getCurrentRedeemer()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getLifetime",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0x81e6e083",
            "signature": "getLifetime()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "bytes32", "name": "ticketId", "type": "bytes32"}
            ],
            "name": "getTimeout",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0x9f1025c6",
            "signature": "getTimeout(bytes32)",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "bytes32", "name": "ticketId", "type": "bytes32"}
            ],
            "name": "keepalive",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0xf0b21a41",
            "signature": "keepalive(bytes32)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "bytes32", "name": "ticketId", "type": "bytes32"}
            ],
            "name": "redeem",
            "outputs": [{"internalType": "bytes32", "name": "", "type": "bytes32"}],
            "selector": "0xeda1122c",
            "signature": "redeem(bytes32)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "bytes32", "name": "requestId", "type": "bytes32"},
                {"internalType": "uint256", "name": "l1BaseFee", "type": "uint256"},
                {"internalType": "uint256", "name": "deposit", "type": "uint256"},
                {"internalType": "uint256", "name": "callvalue", "type": "uint256"},
                {"internalType": "uint256", "name": "gasFeeCap", "type": "uint256"},
                {"internalType": "uint64", "name": "gasLimit", "type": "uint64"},
                {
                    "internalType": "uint256",
                    "name": "maxSubmissionFee",
                    "type": "uint256",
                },
                {
                    "internalType": "address",
                    "name": "feeRefundAddress",
                    "type": "address",
                },
                {"internalType": "address", "name": "beneficiary", "type": "address"},
                {"internalType": "address", "name": "retryTo", "type": "address"},
                {"internalType": "bytes", "name": "retryData", "type": "bytes"},
            ],
            "name": "submitRetryable",
            "outputs": [],
            "selector": "0xc9f95d32",
            "signature": "submitRetryable(bytes32,uint256,uint256,uint256,uint256,uint64,uint256,address,address,address,bytes)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
    ],
    "0x000000000000000000000000000000000000006f": {
        "inputs": [],
        "name": "getStats",
        "outputs": [
            {"internalType": "uint256", "name": "", "type": "uint256"},
            {"internalType": "uint256", "name": "", "type": "uint256"},
            {"internalType": "uint256", "name": "", "type": "uint256"},
            {"internalType": "uint256", "name": "", "type": "uint256"},
            {"internalType": "uint256", "name": "", "type": "uint256"},
            {"internalType": "uint256", "name": "", "type": "uint256"},
        ],
        "selector": "0xc59d4847",
        "signature": "getStats()",
        "stateMutability": "view",
        "type": "function",
    },
    "0x0000000000000000000000000000000000000070": [
        {
            "anonymous": False,
            "inputs": [
                {
                    "indexed": True,
                    "internalType": "bytes4",
                    "name": "method",
                    "type": "bytes4",
                },
                {
                    "indexed": True,
                    "internalType": "address",
                    "name": "owner",
                    "type": "address",
                },
                {
                    "indexed": False,
                    "internalType": "bytes",
                    "name": "data",
                    "type": "bytes",
                },
            ],
            "name": "OwnerActs",
            "selector": "0x3c9e6a772755407311e3b35b3ee56799df8f87395941b3a658eee9e08a67ebda",
            "signature": "OwnerActs(bytes4,address,bytes)",
            "type": "event",
        },
        {
            "inputs": [
                {"internalType": "address", "name": "newOwner", "type": "address"}
            ],
            "name": "addChainOwner",
            "outputs": [],
            "selector": "0x481f8dbf",
            "signature": "addChainOwner(address)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getAllChainOwners",
            "outputs": [{"internalType": "address[]", "name": "", "type": "address[]"}],
            "selector": "0x516b4e0f",
            "signature": "getAllChainOwners()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getInfraFeeAccount",
            "outputs": [{"internalType": "address", "name": "", "type": "address"}],
            "selector": "0xee95a824",
            "signature": "getInfraFeeAccount()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "getNetworkFeeAccount",
            "outputs": [{"internalType": "address", "name": "", "type": "address"}],
            "selector": "0x2d9125e9",
            "signature": "getNetworkFeeAccount()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [{"internalType": "address", "name": "addr", "type": "address"}],
            "name": "isChainOwner",
            "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
            "selector": "0x26ef7f68",
            "signature": "isChainOwner(address)",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [
                {
                    "internalType": "uint256",
                    "name": "maxWeiToRelease",
                    "type": "uint256",
                }
            ],
            "name": "releaseL1PricerSurplusFunds",
            "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
            "selector": "0x314bcf05",
            "signature": "releaseL1PricerSurplusFunds(uint256)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "address", "name": "ownerToRemove", "type": "address"}
            ],
            "name": "removeChainOwner",
            "outputs": [],
            "selector": "0x8792701a",
            "signature": "removeChainOwner(address)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "uint64", "name": "newVersion", "type": "uint64"},
                {"internalType": "uint64", "name": "timestamp", "type": "uint64"},
            ],
            "name": "scheduleArbOSUpgrade",
            "outputs": [],
            "selector": "0xe388b381",
            "signature": "scheduleArbOSUpgrade(uint64,uint64)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [{"internalType": "uint64", "name": "cap", "type": "uint64"}],
            "name": "setAmortizedCostCapBips",
            "outputs": [],
            "selector": "0x56191cc3",
            "signature": "setAmortizedCostCapBips(uint64)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [
                {
                    "internalType": "address",
                    "name": "newInfraFeeAccount",
                    "type": "address",
                }
            ],
            "name": "setInfraFeeAccount",
            "outputs": [],
            "selector": "0x57f585db",
            "signature": "setInfraFeeAccount(address)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [{"internalType": "uint64", "name": "inertia", "type": "uint64"}],
            "name": "setL1BaseFeeEstimateInertia",
            "outputs": [],
            "selector": "0x718f7805",
            "signature": "setL1BaseFeeEstimateInertia(uint64)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "uint256", "name": "pricePerUnit", "type": "uint256"}
            ],
            "name": "setL1PricePerUnit",
            "outputs": [],
            "selector": "0x2b352fae",
            "signature": "setL1PricePerUnit(uint256)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [
                {
                    "internalType": "uint256",
                    "name": "equilibrationUnits",
                    "type": "uint256",
                }
            ],
            "name": "setL1PricingEquilibrationUnits",
            "outputs": [],
            "selector": "0x152db696",
            "signature": "setL1PricingEquilibrationUnits(uint256)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [{"internalType": "uint64", "name": "inertia", "type": "uint64"}],
            "name": "setL1PricingInertia",
            "outputs": [],
            "selector": "0x775a82e9",
            "signature": "setL1PricingInertia(uint64)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "uint64", "name": "weiPerUnit", "type": "uint64"}
            ],
            "name": "setL1PricingRewardRate",
            "outputs": [],
            "selector": "0xf6739500",
            "signature": "setL1PricingRewardRate(uint64)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "address", "name": "recipient", "type": "address"}
            ],
            "name": "setL1PricingRewardRecipient",
            "outputs": [],
            "selector": "0x934be07d",
            "signature": "setL1PricingRewardRecipient(address)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "uint256", "name": "priceInWei", "type": "uint256"}
            ],
            "name": "setL2BaseFee",
            "outputs": [],
            "selector": "0xd99bc80e",
            "signature": "setL2BaseFee(uint256)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [{"internalType": "uint64", "name": "sec", "type": "uint64"}],
            "name": "setL2GasBacklogTolerance",
            "outputs": [],
            "selector": "0x198e7157",
            "signature": "setL2GasBacklogTolerance(uint64)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [{"internalType": "uint64", "name": "sec", "type": "uint64"}],
            "name": "setL2GasPricingInertia",
            "outputs": [],
            "selector": "0x3fd62a29",
            "signature": "setL2GasPricingInertia(uint64)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [{"internalType": "uint64", "name": "limit", "type": "uint64"}],
            "name": "setMaxTxGasLimit",
            "outputs": [],
            "selector": "0x39673611",
            "signature": "setMaxTxGasLimit(uint64)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "uint256", "name": "priceInWei", "type": "uint256"}
            ],
            "name": "setMinimumL2BaseFee",
            "outputs": [],
            "selector": "0xa0188cdb",
            "signature": "setMinimumL2BaseFee(uint256)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [
                {
                    "internalType": "address",
                    "name": "newNetworkFeeAccount",
                    "type": "address",
                }
            ],
            "name": "setNetworkFeeAccount",
            "outputs": [],
            "selector": "0xfcdde2b4",
            "signature": "setNetworkFeeAccount(address)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [{"internalType": "int64", "name": "cost", "type": "int64"}],
            "name": "setPerBatchGasCharge",
            "outputs": [],
            "selector": "0xfad7f20b",
            "signature": "setPerBatchGasCharge(int64)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [{"internalType": "uint64", "name": "limit", "type": "uint64"}],
            "name": "setSpeedLimit",
            "outputs": [],
            "selector": "0x4d7a060d",
            "signature": "setSpeedLimit(uint64)",
            "stateMutability": "nonpayable",
            "type": "function",
        },
    ],
    "0x00000000000000000000000000000000000000ff": [
        {
            "inputs": [
                {"internalType": "uint64", "name": "", "type": "uint64"},
                {"internalType": "string", "name": "", "type": "string"},
                {"internalType": "bool", "name": "", "type": "bool"},
            ],
            "name": "Custom",
            "selector": "0x1753067f",
            "signature": "Custom(uint64,string,bool)",
            "type": "error",
        },
        {
            "inputs": [],
            "name": "Unused",
            "selector": "0x3a66de7d",
            "signature": "Unused()",
            "type": "error",
        },
        {
            "anonymous": False,
            "inputs": [
                {
                    "indexed": False,
                    "internalType": "bool",
                    "name": "flag",
                    "type": "bool",
                },
                {
                    "indexed": True,
                    "internalType": "bytes32",
                    "name": "value",
                    "type": "bytes32",
                },
            ],
            "name": "Basic",
            "selector": "0x93c1309077578d0b9ed1398956be51f0c6e1fcc0b91d899836148550215acfe2",
            "signature": "Basic(bool,bytes32)",
            "type": "event",
        },
        {
            "anonymous": False,
            "inputs": [
                {
                    "indexed": True,
                    "internalType": "bool",
                    "name": "flag",
                    "type": "bool",
                },
                {
                    "indexed": False,
                    "internalType": "bool",
                    "name": "not",
                    "type": "bool",
                },
                {
                    "indexed": True,
                    "internalType": "bytes32",
                    "name": "value",
                    "type": "bytes32",
                },
                {
                    "indexed": False,
                    "internalType": "address",
                    "name": "conn",
                    "type": "address",
                },
                {
                    "indexed": True,
                    "internalType": "address",
                    "name": "caller",
                    "type": "address",
                },
            ],
            "name": "Mixed",
            "selector": "0xa6059246508753631072a6a59c1127af99d3f4cc0f8d6370d4fae122b1dd4eaf",
            "signature": "Mixed(bool,bool,bytes32,address,address)",
            "type": "event",
        },
        {
            "anonymous": False,
            "inputs": [
                {
                    "indexed": True,
                    "internalType": "bool",
                    "name": "flag",
                    "type": "bool",
                },
                {
                    "indexed": True,
                    "internalType": "address",
                    "name": "field",
                    "type": "address",
                },
                {
                    "indexed": False,
                    "internalType": "uint24",
                    "name": "number",
                    "type": "uint24",
                },
                {
                    "indexed": False,
                    "internalType": "bytes32",
                    "name": "value",
                    "type": "bytes32",
                },
                {
                    "indexed": False,
                    "internalType": "bytes",
                    "name": "store",
                    "type": "bytes",
                },
            ],
            "name": "Store",
            "selector": "0x9be442d880b83e5d6db765f303a0602546662e34a066734a19a7ee929c028d95",
            "signature": "Store(bool,address,uint24,bytes32,bytes)",
            "type": "event",
        },
        {
            "inputs": [],
            "name": "becomeChainOwner",
            "outputs": [],
            "selector": "0x0e5bbc11",
            "signature": "becomeChainOwner()",
            "stateMutability": "nonpayable",
            "type": "function",
        },
        {
            "inputs": [{"internalType": "uint64", "name": "number", "type": "uint64"}],
            "name": "customRevert",
            "outputs": [],
            "selector": "0x7ea89f8b",
            "signature": "customRevert(uint64)",
            "stateMutability": "pure",
            "type": "function",
        },
        {
            "inputs": [
                {"internalType": "bool", "name": "flag", "type": "bool"},
                {"internalType": "bytes32", "name": "value", "type": "bytes32"},
            ],
            "name": "events",
            "outputs": [
                {"internalType": "address", "name": "", "type": "address"},
                {"internalType": "uint256", "name": "", "type": "uint256"},
            ],
            "selector": "0x7b9963ef",
            "signature": "events(bool,bytes32)",
            "stateMutability": "payable",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "eventsView",
            "outputs": [],
            "selector": "0x8e5f30ab",
            "signature": "eventsView()",
            "stateMutability": "view",
            "type": "function",
        },
        {
            "inputs": [],
            "name": "legacyError",
            "outputs": [],
            "selector": "0x1e48fe82",
            "signature": "legacyError()",
            "stateMutability": "pure",
            "type": "function",
        },
    ],
}
