abi = [
    {
        "type": "constructor",
        "inputs": [
            {
                "name": "params",
                "type": "tuple",
                "components": [
                    {"name": "permit2", "type": "address", "internalType": "address"},
                    {"name": "weth9", "type": "address", "internalType": "address"},
                    {"name": "seaport", "type": "address", "internalType": "address"},
                    {"name": "nftxZap", "type": "address", "internalType": "address"},
                    {"name": "x2y2", "type": "address", "internalType": "address"},
                    {
                        "name": "foundation",
                        "type": "address",
                        "internalType": "address",
                    },
                    {"name": "sudoswap", "type": "address", "internalType": "address"},
                    {"name": "nft20Zap", "type": "address", "internalType": "address"},
                    {
                        "name": "cryptopunks",
                        "type": "address",
                        "internalType": "address",
                    },
                    {"name": "looksRare", "type": "address", "internalType": "address"},
                    {
                        "name": "routerRewardsDistributor",
                        "type": "address",
                        "internalType": "address",
                    },
                    {
                        "name": "looksRareRewardsDistributor",
                        "type": "address",
                        "internalType": "address",
                    },
                    {
                        "name": "looksRareToken",
                        "type": "address",
                        "internalType": "address",
                    },
                    {"name": "v2Factory", "type": "address", "internalType": "address"},
                    {"name": "v3Factory", "type": "address", "internalType": "address"},
                    {
                        "name": "pairInitCodeHash",
                        "type": "bytes32",
                        "internalType": "bytes32",
                    },
                    {
                        "name": "poolInitCodeHash",
                        "type": "bytes32",
                        "internalType": "bytes32",
                    },
                ],
                "internalType": "struct RouterParameters",
            }
        ],
        "stateMutability": "nonpayable",
    },
    {"name": "ContractLocked", "type": "error", "inputs": []},
    {"name": "ETHNotAccepted", "type": "error", "inputs": []},
    {
        "name": "ExecutionFailed",
        "type": "error",
        "inputs": [
            {"name": "commandIndex", "type": "uint256", "internalType": "uint256"},
            {"name": "message", "type": "bytes", "internalType": "bytes"},
        ],
    },
    {"name": "FromAddressIsNotOwner", "type": "error", "inputs": []},
    {"name": "InsufficientETH", "type": "error", "inputs": []},
    {"name": "InsufficientToken", "type": "error", "inputs": []},
    {"name": "InvalidBips", "type": "error", "inputs": []},
    {
        "name": "InvalidCommandType",
        "type": "error",
        "inputs": [
            {"name": "commandType", "type": "uint256", "internalType": "uint256"}
        ],
    },
    {"name": "InvalidOwnerERC1155", "type": "error", "inputs": []},
    {"name": "InvalidOwnerERC721", "type": "error", "inputs": []},
    {"name": "InvalidPath", "type": "error", "inputs": []},
    {"name": "InvalidReserves", "type": "error", "inputs": []},
    {"name": "LengthMismatch", "type": "error", "inputs": []},
    {"name": "NoSlice", "type": "error", "inputs": []},
    {"name": "SliceOutOfBounds", "type": "error", "inputs": []},
    {"name": "SliceOverflow", "type": "error", "inputs": []},
    {"name": "ToAddressOutOfBounds", "type": "error", "inputs": []},
    {"name": "ToAddressOverflow", "type": "error", "inputs": []},
    {"name": "ToUint24OutOfBounds", "type": "error", "inputs": []},
    {"name": "ToUint24Overflow", "type": "error", "inputs": []},
    {"name": "TransactionDeadlinePassed", "type": "error", "inputs": []},
    {"name": "UnableToClaim", "type": "error", "inputs": []},
    {"name": "UnsafeCast", "type": "error", "inputs": []},
    {"name": "V2InvalidPath", "type": "error", "inputs": []},
    {"name": "V2TooLittleReceived", "type": "error", "inputs": []},
    {"name": "V2TooMuchRequested", "type": "error", "inputs": []},
    {"name": "V3InvalidAmountOut", "type": "error", "inputs": []},
    {"name": "V3InvalidCaller", "type": "error", "inputs": []},
    {"name": "V3InvalidSwap", "type": "error", "inputs": []},
    {"name": "V3TooLittleReceived", "type": "error", "inputs": []},
    {"name": "V3TooMuchRequested", "type": "error", "inputs": []},
    {
        "name": "RewardsSent",
        "type": "event",
        "inputs": [
            {
                "name": "amount",
                "type": "uint256",
                "indexed": False,
                "internalType": "uint256",
            }
        ],
        "anonymous": False,
    },
    {
        "name": "collectRewards",
        "type": "function",
        "inputs": [
            {"name": "looksRareClaim", "type": "bytes", "internalType": "bytes"}
        ],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {
        "name": "execute",
        "type": "function",
        "inputs": [
            {"name": "commands", "type": "bytes", "internalType": "bytes"},
            {"name": "inputs", "type": "bytes[]", "internalType": "bytes[]"},
        ],
        "outputs": [],
        "stateMutability": "payable",
    },
    {
        "name": "execute",
        "type": "function",
        "inputs": [
            {"name": "commands", "type": "bytes", "internalType": "bytes"},
            {"name": "inputs", "type": "bytes[]", "internalType": "bytes[]"},
            {"name": "deadline", "type": "uint256", "internalType": "uint256"},
        ],
        "outputs": [],
        "stateMutability": "payable",
    },
    {
        "name": "onERC1155BatchReceived",
        "type": "function",
        "inputs": [
            {"name": "", "type": "address", "internalType": "address"},
            {"name": "", "type": "address", "internalType": "address"},
            {"name": "", "type": "uint256[]", "internalType": "uint256[]"},
            {"name": "", "type": "uint256[]", "internalType": "uint256[]"},
            {"name": "", "type": "bytes", "internalType": "bytes"},
        ],
        "outputs": [{"name": "", "type": "bytes4", "internalType": "bytes4"}],
        "stateMutability": "pure",
    },
    {
        "name": "onERC1155Received",
        "type": "function",
        "inputs": [
            {"name": "", "type": "address", "internalType": "address"},
            {"name": "", "type": "address", "internalType": "address"},
            {"name": "", "type": "uint256", "internalType": "uint256"},
            {"name": "", "type": "uint256", "internalType": "uint256"},
            {"name": "", "type": "bytes", "internalType": "bytes"},
        ],
        "outputs": [{"name": "", "type": "bytes4", "internalType": "bytes4"}],
        "stateMutability": "pure",
    },
    {
        "name": "onERC721Received",
        "type": "function",
        "inputs": [
            {"name": "", "type": "address", "internalType": "address"},
            {"name": "", "type": "address", "internalType": "address"},
            {"name": "", "type": "uint256", "internalType": "uint256"},
            {"name": "", "type": "bytes", "internalType": "bytes"},
        ],
        "outputs": [{"name": "", "type": "bytes4", "internalType": "bytes4"}],
        "stateMutability": "pure",
    },
    {
        "name": "supportsInterface",
        "type": "function",
        "inputs": [{"name": "interfaceId", "type": "bytes4", "internalType": "bytes4"}],
        "outputs": [{"name": "", "type": "bool", "internalType": "bool"}],
        "stateMutability": "pure",
    },
    {
        "name": "uniswapV3SwapCallback",
        "type": "function",
        "inputs": [
            {"name": "amount0Delta", "type": "int256", "internalType": "int256"},
            {"name": "amount1Delta", "type": "int256", "internalType": "int256"},
            {"name": "data", "type": "bytes", "internalType": "bytes"},
        ],
        "outputs": [],
        "stateMutability": "nonpayable",
    },
    {"type": "receive", "stateMutability": "payable"},
]
