#!/usr/bin/env python3

abi = [
    {
        "name": "name",
        "type": "function",
        "inputs": [],
        "outputs": [{"name": "", "type": "string"}],
        "payable": False,
        "constant": True,
        "stateMutability": "view",
    },
    {
        "name": "approve",
        "type": "function",
        "inputs": [
            {"name": "guy", "type": "address"},
            {"name": "wad", "type": "uint256"},
        ],
        "outputs": [{"name": "", "type": "bool"}],
        "payable": False,
        "constant": False,
        "stateMutability": "nonpayable",
    },
    {
        "name": "totalSupply",
        "type": "function",
        "inputs": [],
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "constant": True,
        "stateMutability": "view",
    },
    {
        "name": "transferFrom",
        "type": "function",
        "inputs": [
            {"name": "src", "type": "address"},
            {"name": "dst", "type": "address"},
            {"name": "wad", "type": "uint256"},
        ],
        "outputs": [{"name": "", "type": "bool"}],
        "payable": False,
        "constant": False,
        "stateMutability": "nonpayable",
    },
    {
        "name": "withdraw",
        "type": "function",
        "inputs": [{"name": "wad", "type": "uint256"}],
        "outputs": [],
        "payable": False,
        "constant": False,
        "stateMutability": "nonpayable",
    },
    {
        "name": "decimals",
        "type": "function",
        "inputs": [],
        "outputs": [{"name": "", "type": "uint8"}],
        "payable": False,
        "constant": True,
        "stateMutability": "view",
    },
    {
        "name": "balanceOf",
        "type": "function",
        "inputs": [{"name": "", "type": "address"}],
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "constant": True,
        "stateMutability": "view",
    },
    {
        "name": "symbol",
        "type": "function",
        "inputs": [],
        "outputs": [{"name": "", "type": "string"}],
        "payable": False,
        "constant": True,
        "stateMutability": "view",
    },
    {
        "name": "transfer",
        "type": "function",
        "inputs": [
            {"name": "dst", "type": "address"},
            {"name": "wad", "type": "uint256"},
        ],
        "outputs": [{"name": "", "type": "bool"}],
        "payable": False,
        "constant": False,
        "stateMutability": "nonpayable",
    },
    {
        "name": "deposit",
        "type": "function",
        "inputs": [],
        "outputs": [],
        "payable": True,
        "constant": False,
        "stateMutability": "payable",
    },
    {
        "name": "allowance",
        "type": "function",
        "inputs": [{"name": "", "type": "address"}, {"name": "", "type": "address"}],
        "outputs": [{"name": "", "type": "uint256"}],
        "payable": False,
        "constant": True,
        "stateMutability": "view",
    },
    {"type": "fallback", "payable": True, "stateMutability": "payable"},
    {
        "name": "Approval",
        "type": "event",
        "inputs": [
            {"name": "src", "type": "address", "indexed": True},
            {"name": "guy", "type": "address", "indexed": True},
            {"name": "wad", "type": "uint256", "indexed": False},
        ],
        "anonymous": False,
    },
    {
        "name": "Transfer",
        "type": "event",
        "inputs": [
            {"name": "src", "type": "address", "indexed": True},
            {"name": "dst", "type": "address", "indexed": True},
            {"name": "wad", "type": "uint256", "indexed": False},
        ],
        "anonymous": False,
    },
    {
        "name": "Deposit",
        "type": "event",
        "inputs": [
            {"name": "dst", "type": "address", "indexed": True},
            {"name": "wad", "type": "uint256", "indexed": False},
        ],
        "anonymous": False,
    },
    {
        "name": "Withdrawal",
        "type": "event",
        "inputs": [
            {"name": "src", "type": "address", "indexed": True},
            {"name": "wad", "type": "uint256", "indexed": False},
        ],
        "anonymous": False,
    },
]
